### ISSUE TITLE
Mod (from GitHub) not working

### ISSUE THREAD

**Issue by jarixofficial** [Trawis/T4A11#14]
I downloaded the mod from GitHub, made a new folder named "DLLMods", and transferred the "Trainer_v4" folder into it.
Opened up the game, opened the console, and typed in "RELOAD_DLL_MOD Trainer_v4".
I was greeted with this error message:
----------------
>Error loading dll mod Trainer_v4 with load errors:
System.Exception: [CS1729]: The type `SimulatedCompany' does not contain a constructor that takes `6' arguments in
C:\Users\...........\DLLMods\Trainer_v4\TrainerBehaviour.cs at [649, 31]
----------------
(version Alpha 11.4.8)
Looking forward to your reply. Thanks!

**Comment by Trawis** [comment]
I can't reproduce it, I recompiled code successfully. Are you sure that you are on A11?

**Comment by jarixofficial** [comment]
11.4.8

**Comment by Trawis** [comment]
Update game to Alpha 11.6.7
