### ISSUE TITLE
TrainerBehavior.cs ruined the mod?

### ISSUE THREAD

**Issue by ichxorya** [Trawis/T4A11#15]
I'm not a C# programmer, so let's get this straight. I can't play the mod because there was some errors in this file.
What I did was only removing (or to be precisely - "commented") the broken code at the 365th line. Woosh, the mod runs, and it runs smoothly!
Hopes that help!

**Comment by Trawis** [comment]
Thanks, the issue is now resolved. New game update broke the mod.
