### ISSUE TITLE
failed to load mods

### ISSUE THREAD

**Issue by mrazhariq1209** [Trawis/T4A11#3]
I'm using latest software inc but its non-steam
installed it on the correct mods folder but every time I start software inc it just failed to load the mods
other mods worked fine but the trainer v4 failed, is there a missing file? or I installed it on the wrong folder?
here's the log if u need it
[output_log.txt](https://github.com/Trawis/T4A11/files/3724281/output_log.txt)

**Comment by Trawis** [comment]
Did you put "Trainer_v4" folder into "DLL Mods" in Software Inc?

**Comment by mrazhariq1209** [comment]
so i drop it on DLL mods not regular mods folder?

**Comment by mrazhariq1209** [comment]
changed it to dll mods folder but now the mod is not even detected by the game
tried it a couple of times, still error

**Comment by Trawis** [comment]
Create DLLMods folder in Software Inc if you don't have it already, create Trainer_v4 folder and put *.cs downloaded files into that folder. You don't need to compile it.

**Comment by mrazhariq1209** [comment]
ahh, sheet sorry I'm a dumb fuck haha its working now :D
sorry for wasting ur time, and thank you for the amazing mod !! 
keep up the good work ma dude

**Comment by mrazhariq1209** [comment]
i just need to reload the mod from the console..

**Comment by ShadowMasterGo** [comment]
so cant normal mods be used in cracked software inc?
