### ISSUE TITLE
Mod Not Appearing In Game

### ISSUE THREAD

**Issue by APerson1738** [Trawis/T4A11#4]
I Downloaded The Source Files From Github And Compiled It Using VS 2017 Since I Have The Game Not On Steam And I Put The Output (Trainer_v3.dll) In The DLLMods Folder However It Is Not Appearing In The Mods Tab Or If I Type RELOAD_DLL_MOD Trainer_v3.dll Into The Console It Says Mod Not Found.

**Comment by Trawis** [comment]
Trainer v3 is only for Alpha 10, Trainer v4 is for Alpha 11. Create DLLMods folder in Software Inc if you don't have it already, create Trainer_v3/Trainer_v4 folder and put *.cs downloaded files into that folder. You don't need to compile it.

**Comment by APerson1738** [comment]
Ok I did download trainer v4 but the output was trainer_v3.dll thanks for
helping

**Comment by Trawis** [comment]
Is it working now?

**Comment by APerson1738** [comment]
Yes, Only Just Had Chance To Check, It Only Appeared After I Loaded It In The Console Though. Thanks For YOur Help
