### ISSUE TITLE
Fails to load on Alpha 11.4.2

### ISSUE THREAD

**Issue by ThrowsException** [Trawis/T4A11#9]
Error loading dll mod 1884023959 with load errors:
System.Exception: [CS1061]: Type `SimulatedCompany' does not contain a definition for `DistributionDeal' and no extension method `DistributionDeal' of type `SimulatedCompany' could be found. Are you missing an assembly reference? in E:\Games\steamapps\workshop\content\362620\1884023959\TrainerBehaviour.cs at [271, 39]
  at ModController.LoadMod (System.String path, Boolean dll, Boolean force, System.String overrideName) [0x00000] in <filename unknown>:0 

I took away the code https://github.com/Trawis/T4A11/blob/master/Trainer_v4/TrainerBehaviour.cs#L263-L283 and that got it to load at least.

**Comment by Trawis** [comment]
Thank you for reporting. Auto Distribution Deals will be removed temporarily due to new code change in the game.
